object Versions {
    const val agp = "7.1.2"
    const val kotlin = "1.6.10"
    const val detekt = "1.20.0-RC1"

    const val compose = "1.1.1"
    const val activityCompose = "1.4.0"
    const val lifecycle = "2.4.1"
    const val accompanist = "0.24.2-alpha"
    const val navigation = "2.4.1"
    const val hilt = "2.40.5"
    const val hiltNavigationCompose = "1.0.0"
    const val retrofit = "2.9.0"
    const val loggingInterceptor = "5.0.0-alpha.2"
    const val room = "2.4.2"
    const val truth = "1.1.3"
    const val coil = "1.4.0"
    const val mockk = "1.12.2"
    const val lottie = "5.0.1"
    const val mockWebservice = "5.0.0-alpha.2"
    const val paging = "3.1.0"
    const val leakcanary = "2.8.1"
}